version: 1
default_environment: dev
project_id: 8a9c5e0f-1234-4567-890a-bcdef0123456

environments:
  - name: dev
  - name: prod

# Shared configuration
_bm_units: &bm_units
  - "2__DSTAT001"
  - "2__ESTAT003"
  - "2__ESTAT001"
  - "2__LSTAT003"
  - "2__HSTAT003"

plugins:
  extractors:
    - name: tap-nationalgas
      namespace: tap_nationalgas
      pip_url: -e ./plugins/tap-nationalgas
      executable: tap-nationalgas
      capabilities:
        - state
        - catalog
        - discover
      settings:
        - name: api_url
          kind: string
          value: https://api.nationalgas.com/operationaldata/v1/gasquality/latestdata
        - name: start_date
          kind: date_iso8601
          value: "2024-01-01T00:00:00Z"

    - name: tap-elexon-disebsp
      namespace: tap_elexon_disebsp
      pip_url: -e ./plugins/tap-elexon-disebsp
      executable: tap-elexon-disebsp
      capabilities:
        - state
        - catalog
        - discover
      settings:
        - name: api_url
          kind: string
          value: https://data.elexon.co.uk/bmrs/api/v1/balancing/settlement/system-prices
        - name: start_date
          kind: date_iso8601
          value: "2024-01-01T00:00:00Z"

    - name: tap-elexon-bm
      namespace: tap_elexon_bm
      pip_url: -e ./plugins/tap-elexon-bm
      executable: tap-elexon-bm
      capabilities:
        - state
        - catalog
        - discover
      settings:
        - name: api_url
          kind: string
          value: https://data.elexon.co.uk/bmrs/api/v1
        - name: bm_units
          kind: array
          value: *bm_units
        - name: start_date
          kind: date_iso8601
          value: "2024-01-01T00:00:00Z"

    - name: tap-elexon-midp
      namespace: tap_elexon_midp
      pip_url: -e ./plugins/tap-elexon-midp
      executable: tap-elexon-midp
      capabilities:
        - state
        - catalog
        - discover
      settings:
        - name: api_url
          kind: string
          value: https://data.elexon.co.uk/bmrs/api/v1/balancing/pricing/market-index
        - name: start_date
          kind: date_iso8601

    - name: tap-elexon-b1610
      namespace: tap_elexon_b1610
      pip_url: -e ./plugins/tap-elexon-b1610
      executable: tap-elexon-b1610
      capabilities:
        - state
        - catalog
        - discover
      settings:
        - name: api_url
          kind: string
          value: https://data.elexon.co.uk/bmrs/api/v1
        - name: bm_units
          kind: array
          value: *bm_units
        - name: start_date
          kind: date_iso8601
          value: "2024-01-01T00:00:00Z"

  loaders:
    - name: target-influxdb
      namespace: target_influxdb
      pip_url: -e ./plugins/target-influxdb
      executable: target-influxdb
      config:
        influxdb_url: ${INFLUXDB_URL}
        influxdb_token: ${INFLUXDB_TOKEN}
        influxdb_org: ${INFLUXDB_ORG}
        influxdb_bucket: ${INFLUXDB_BUCKET}

schedules:
  - name: nationalgas-to-influxdb
    interval: '@every 30m'
    job: nationalgas-to-influxdb

  - name: elexon-disebsp-to-influxdb
    interval: '0 3 * * *'
    job: elexon-disebsp-to-influxdb

  # Disabled until changes are decided
  # - name: elexon-bm-to-influxdb
  #   interval: '@every 30m'
  #   job: elexon-bm-to-influxdb

  - name: elexon-midp-to-influxdb
    interval: '@every 30m'
    job: elexon-midp-to-influxdb

  - name: elexon-b1610-to-influxdb
    interval: '0 3 * * *'
    job: elexon-b1610-to-influxdb

jobs:
  - name: nationalgas-to-influxdb
    tasks:
      - tap-nationalgas target-influxdb

  - name: elexon-disebsp-to-influxdb
    tasks:
      - tap-elexon-disebsp target-influxdb

  # Disabled until changes are decided
  # - name: elexon-bm-to-influxdb
  #   tasks:
  #     - tap-elexon-bm target-influxdb

  - name: elexon-midp-to-influxdb
    tasks:
      - tap-elexon-midp target-influxdb

  - name: elexon-b1610-to-influxdb
    tasks:
      - tap-elexon-b1610 target-influxdb
